import type { TaskItem } from '../types';
import { formatKoreanDate, formatMinutesToText } from './dateUtils';

/**
 * Generates Weekly Summary Report string in Markdown format
 */
export const generateWeeklySummaryMarkdown = (
  tasks: TaskItem[],
  startStr: string,
  endStr: string
): string => {
  const filtered = tasks.filter((t) => t.date >= startStr && t.date <= endStr);
  const startFormatted = formatKoreanDate(startStr);
  const endFormatted = formatKoreanDate(endStr);

  let md = `# 📅 주간 업무 보고서 (${startFormatted} ~ ${endFormatted})\n\n`;

  if (filtered.length === 0) {
    md += `해당 기간에 등록된 업무 기록이 없습니다.\n`;
    return md;
  }

  // Calculate stats
  const totalTasks = filtered.length;
  const completedTasks = filtered.filter((t) => t.completed).length;
  const totalMinutes = filtered.reduce((acc, t) => acc + (t.timeSpentMinutes || 0), 0);

  md += `### 📊 주간 성과 요약\n`;
  md += `- **총 진행 업무:** ${totalTasks}건 (완료 ${completedTasks}건 / 진행 중 ${totalTasks - completedTasks}건)\n`;
  if (totalMinutes > 0) {
    md += `- **총 소요 시간:** ${formatMinutesToText(totalMinutes)}\n`;
  }
  md += `\n---\n\n`;

  // Group by category
  const categories = Array.from(new Set(filtered.map((t) => t.category || '기타')));

  md += `### 📌 카테고리별 세부 실적\n\n`;

  categories.forEach((cat) => {
    const catTasks = filtered.filter((t) => (t.category || '기타') === cat);
    md += `#### 🏷️ [${cat}]\n`;
    catTasks.forEach((t) => {
      const statusCheck = t.completed ? '✅' : '⏳';
      const timeStr = t.timeSpentMinutes ? ` (${formatMinutesToText(t.timeSpentMinutes)})` : '';
      const descStr = t.description ? ` - *${t.description}*` : '';
      md += `- ${statusCheck} **${t.title}**${timeStr}${descStr} \`[${t.date}]\` \n`;
    });
    md += `\n`;
  });

  md += `---\n*Generated by SyncDaily (https://syncdaily.app)*\n`;
  return md;
};

/**
 * Generates Weekly Summary Report string in Plain Text format (suited for emails/slack)
 */
export const generateWeeklySummaryText = (
  tasks: TaskItem[],
  startStr: string,
  endStr: string
): string => {
  const filtered = tasks.filter((t) => t.date >= startStr && t.date <= endStr);
  const startFormatted = formatKoreanDate(startStr);
  const endFormatted = formatKoreanDate(endStr);

  let txt = `[주간 업무 보고서] (${startFormatted} ~ ${endFormatted})\n\n`;

  if (filtered.length === 0) {
    txt += `해당 기간에 등록된 업무 기록이 없습니다.\n`;
    return txt;
  }

  const totalTasks = filtered.length;
  const completedTasks = filtered.filter((t) => t.completed).length;
  const totalMinutes = filtered.reduce((acc, t) => acc + (t.timeSpentMinutes || 0), 0);

  txt += `■ 주간 요약: 총 ${totalTasks}건 (완료 ${completedTasks}건, 진행중 ${totalTasks - completedTasks}건)`;
  if (totalMinutes > 0) {
    txt += ` | 총 소요시간: ${formatMinutesToText(totalMinutes)}`;
  }
  txt += `\n\n`;

  const categories = Array.from(new Set(filtered.map((t) => t.category || '기타')));

  categories.forEach((cat) => {
    const catTasks = filtered.filter((t) => (t.category || '기타') === cat);
    txt += `▶ [${cat}]\n`;
    catTasks.forEach((t) => {
      const statusStr = t.completed ? '[완료]' : '[진행중]';
      const timeStr = t.timeSpentMinutes ? ` (${formatMinutesToText(t.timeSpentMinutes)})` : '';
      const descStr = t.description ? ` : ${t.description}` : '';
      txt += `  • ${statusStr} ${t.title}${timeStr}${descStr} (${t.date})\n`;
    });
    txt += `\n`;
  });

  txt += `----------------------------------------\n작성도구: SyncDaily App`;
  return txt;
};

/**
 * Triggers file download in browser
 */
export const downloadFile = (filename: string, content: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Download Tasks as JSON backup file
 */
export const exportTasksAsJSON = (tasks: TaskItem[]) => {
  const jsonStr = JSON.stringify(tasks, null, 2);
  const filename = `SyncDaily_Backup_${new Date().toISOString().slice(0, 10)}.json`;
  downloadFile(filename, jsonStr, 'application/json');
};

/**
 * Download Tasks as Markdown document
 */
export const exportTasksAsMarkdown = (tasks: TaskItem[]) => {
  let md = `# 📝 SyncDaily 업무 기록 백업 (${new Date().toISOString().slice(0, 10)})\n\n`;
  
  // Sort tasks descending by date
  const sorted = [...tasks].sort((a, b) => b.date.localeCompare(a.date));

  let currentDate = '';
  sorted.forEach((t) => {
    if (t.date !== currentDate) {
      currentDate = t.date;
      md += `\n## 📅 ${formatKoreanDate(currentDate)}\n\n`;
    }
    const status = t.completed ? '[x]' : '[ ]';
    const tag = t.category ? `\`[${t.category}]\`` : '';
    const time = t.timeSpentMinutes ? `(${formatMinutesToText(t.timeSpentMinutes)})` : '';
    md += `- ${status} ${t.title} ${tag} ${time}\n`;
    if (t.description) {
      md += `  > ${t.description}\n`;
    }
  });

  const filename = `SyncDaily_Tasks_${new Date().toISOString().slice(0, 10)}.md`;
  downloadFile(filename, md, 'text/markdown');
};

/**
 * Download Tasks as Plain Text document
 */
export const exportTasksAsTXT = (tasks: TaskItem[]) => {
  let txt = `SyncDaily 업무 전체 백업 목록 (${new Date().toISOString().slice(0, 10)})\n========================================\n\n`;
  const sorted = [...tasks].sort((a, b) => b.date.localeCompare(a.date));

  sorted.forEach((t) => {
    txt += `[${t.date}] [${t.category || '기타'}] ${t.completed ? '✓ 완료' : '○ 진행중'} - ${t.title}\n`;
    if (t.timeSpentMinutes) txt += `  소요시간: ${formatMinutesToText(t.timeSpentMinutes)}\n`;
    if (t.description) txt += `  메모: ${t.description}\n`;
    txt += `----------------------------------------\n`;
  });

  const filename = `SyncDaily_Tasks_${new Date().toISOString().slice(0, 10)}.txt`;
  downloadFile(filename, txt, 'text/plain');
};
